# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47c825f1bf32a0f581f38d65d59a02b398346c2971434e1c47d609d3d6deffabe0f64c5ab55751840fc452c4f0de9ee4d735b82a27e8599bf0ce226417f8d7f2

test:
  secret_key_base: 550c8907d3b7c29e50ad6b8e469485f841533f645cab74d3c816c7923ba09efd619bba3758404666c0c673c4638716b3b83a968ef1cc7c7ca8e5dd779e3c59f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
